### ISSUE TITLE
Wird an der Integration noch gearbeitet?

### ISSUE THREAD

**Issue by ibbalex** [Skipperro/enpal-homeassistant#1]
Hallo, es fehlen leider noch einige für mich wichtige Punkte (Beispielsweise Füllstand Akku) außerdem können sie Sensoren nicht fehlerfrei ins Energy Dashboard übernommen werden.
daher meine Frage wird an der Integration noch gearbeitet?

LG Alex

**Comment by gickowtf** [comment]
Moin Alex, ich habe soeben die Integration für mich gangbar gemacht und ich werde auch so wie von dir gewünscht den Füllstand der Batterie in Prozent Einpflegen.

Falls deiner seits noch Interesse besteht melde dich mal. bin noch ziemlich neu in HA und brauch dementsprechend Inspirationen ;)

**Comment by Skipperro** [comment]
Ich will das alles noch machen, aber ich habe Info von Enpal bekommen, das die wollen ganze API und Daten Struktur anderes machen. Alles was ich heute programmiere wird gleich obsolete.

Was Sie machen können ist an Enpal schreiben und wegen bessere Support für Home Assistant fragen. Dann bekommen wir das wahrscheinlich schneller.

**Comment by Excellsior1985** [comment]
Hey ja das Interesse besteht auf jeden Fall!

Wenn ich irgendwie unterstützen kann sag gerne bescheid!

LG


Von: gickowtf ***@***.***>
Gesendet: Montag, 2. Oktober 2023 21:09
An: Skipperro/enpal-homeassistant ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: Re: [Skipperro/enpal-homeassistant] Wird an der Integration noch gearbeitet? (Issue #1)


Moin Alex, ich habe soeben die Integration für mich gangbar gemacht und ich werde auch so wie von dir gewünscht den Füllstand der Batterie in Prozent Einpflegen.

Falls deiner seits noch Interesse besteht melde dich mal. bin noch ziemlich neu in HA und brauch dementsprechend Inspirationen ;)

**Comment by Skipperro** [comment]
@gickowtf Natürlich ich habe nichts gegen neue Public-Fork. 
Kannst du mir sagen wo hast du Token geufunden? 
Ich bekomme es immer via Enpal Support, aber es läuft immer ab nach einige Zeit und ich muss ständig um neue bitten :/

**Comment by gickowtf** [comment]
@Skipperro 
![Bildschirmfoto 2023-10-03 um 19 38 37](https://github.com/Skipperro/enpal-homeassistant/assets/47464154/dd95258b-7564-45a2-9ea8-03137873f833)

Ich habe unter der IP der EnpalBox ein kleines Web Interface und dort unter dem Punkt config im unteren Bereich findet man influx dort steht dann auch der token sowie Bucket und Organisation.
Sofern man nicht die nötigen Python skills hat um zu sehen wie die einzelnen _fields heissen steht dies z.B. im Bereich Messages!

... ok vielen dank dann probiere ich mich mal in dem Public-Fork

**Comment by Skipperro** [comment]
@gickowtf Kann ich fragen wann hast du deine Solaranlage gebaut? Du hast dort viel mehr als ich.
Mein Web-Interface auf Port 80 sieht so aus:
![image](https://github.com/Skipperro/enpal-homeassistant/assets/20705647/2c81cd00-511a-46f3-b96d-2d4b6a8aa506)
Dazu habe ich nur Grafana auf Port 3080 :(

**Comment by gickowtf** [comment]
Oha ja da habe ich mal von gelesen das ältere Enpal Anlagen ein anderes Web-Interface haben... meine Anlage ist noch relativ jung und wurde im Juli installiert. :( das ist wirklich schade. Und echt blöd von Enpal gelöst!

**Comment by Skipperro** [comment]
Also.... dann @ibbalex wartet schon seit März bis ich diese Integration weiter entwickle, ich warte auf Enpal, bis die neue System freigeben und sieht so aus das neue System ist schon da, nur ich als ältere Kunde habe kein Zugriff dafür und deswegen kann es nicht entwickeln.

Danke für Info @gickowtf. Ich schreibe gleich "nette" Email an Enpal.

**Comment by OlwinFroon** [comment]
Servus,
die Grafana-Variante scheint in der alten (grauen) Variante der Enpal-Box zu Hause zu sein. Die hab ich auch.
Die neue (weiße) Box kann wohl etliches mehr.
Ich hab gerade meine Mail mit Zugangsdaten für die  (alte) InfluxDB bekommen, zusammen mit dieser Info:

_Wir arbeiten in diesem Jahr an einer größeren Umstrukturierung unserer Lösung die dann auch auf Ihrem System ausgerollt wird. Dies wird dann auf
jeden Fall auch die Influx DB betreffen. Sie müssten dann noch einmal Anpassungen an Ihrem System vornehmen._

Da bin ich ja mal gespannt...

P.S.: Ich finde Eure Integrationen nicht in HACS

**Comment by gickowtf** [comment]
Du musst das repository in HACS einpflegen. Sprich oben rechts auf die drei Punkte und dort auf repositorys… da dann einfach https://github.com/Skipperro/enpal-homeassistant/ eintippen.

**Comment by OlwinFroon** [comment]
... facepalm moment ...
Klar. Danke.

Ich seh das richtig, für die alte Box krieg ich nur das was Skipperro gemacht hat, für Deine Variante bräuchte ich die neue Box bzw. neue Firmware?

**Comment by gickowtf** [comment]
Ja genau 👍 ich weiß auch nicht warum enpal da so langsam arbeitet… aber laut meinen Infos soll das Update dann immens stark sein.

**Comment by OlwinFroon** [comment]
Na wenn ich an einem Update arbeiten würde das mehrere tausend Kunden gleichzeitig betrifft wäre ich auch sorgfältig + vorsichtig = langsam :D

Whatever: Integration installiert, HA neu gestartet, IP und Token eingetragen, aber nichts geht:
`2024-01-02 12:30:09.639 ERROR (MainThread) [homeassistant.components.sensor] enpal: Not adding entity with invalid device info: Invalid device info {'default_manufacturer': 'Enpal', 'default_name': 'Enpal Solar Installation', 'entry_type': <DeviceEntryType.SERVICE: 'service'>, 'identifiers': {('enpal', 'enpal')}, 'sw_version': '0.1.0'} for 'enpal' config entry: device info needs to either describe a device, link to existing device or provide extra information.`

**Comment by OlwinFroon** [comment]
Das ist vermutlich nicht der beste Ort für so eine Diskussion. Erwischt man Euch auf Discord, Slack oder Signal?

**Comment by Skipperro** [comment]
Seit 2 Monate schreibe ich Email an Enpal jede Woche - Direkt an Software Entwicklungs Team.
Mein Update ist schon seit 1 Jahr geplant. Es war bei mir sogar Techniker der hat ganze Computer getauscht. Leider nach dem tausch habe ich immer noch alte Version.

@OlwinFroon meine alte Enpal Integration funktioniert jetzt auch nicht, weil der Token kein richtige Rechte für das InfluxDB hat und neue Version von @gickowtf funktioniert bei mir auch nicht, weil Update von Enpal fehlt.

Also, obwohl ich habe diese Integration entwickelt, so sieht es bei mir jetzt aus: :face_with_spiral_eyes: 
![image](https://github.com/Skipperro/enpal-homeassistant/assets/20705647/8b4f0c36-7f87-4ca6-97ae-a831465ecdc9)

**Comment by OlwinFroon** [comment]
:( 
Schlappes Bild, Enpal. Schlappes Bild. 
Aber keine große Überraschung, leider.

Ich hab neben dem Token auch Credentials für die InfluxDB UI auf der Box bekommen (192.168.178.xx:8086) und konnte mich da auch anmelden.

Leider habe ich keine Ahnung von InfluxDB, aber wo ich auch rumgespielt habe, Daten habe ich keine gesehen.

**Comment by OlwinFroon** [comment]
Okay. Etwas gelesen, mehr rumgespielt.

In der Influx UI bekomme ich mit diesem Query
```
from(bucket: "my-new-bucket")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "inverterTemperature" or r["_measurement"] == "phaseCurrentAc" or r["_measurement"] == "intoGridEnergy" or r["_measurement"] == "gridFrequency" or r["_measurement"] == "fromGridEnergy" or r["_measurement"] == "Gesamtleistung" or r["_measurement"] == "LeistungDc" or r["_measurement"] == "aggregated" or r["_measurement"] == "consumptionEnergy" or r["_measurement"] == "deviceStatus" or r["_measurement"] == "phasePowerAc" or r["_measurement"] == "phaseVoltageAc" or r["_measurement"] == "productionCurrentDc" or r["_measurement"] == "productionVoltageDc")
  |> filter(fn: (r) => r["_field"] == "Temperature" or r["_field"] == "Phase1" or r["_field"] == "Phase2" or r["_field"] == "Phase3" or r["_field"] == "Verbrauch" or r["_field"] == "Frequenz" or r["_field"] == "Produktion" or r["_field"] == "String1" or r["_field"] == "String2" or r["_field"] == "Total" or r["_field"] == "DeviceStatus")
  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)
  |> yield(name: "last")
```
Daten. Das Token habe ich da auch gefunden, es stimmt mit dem überein das die mir geschickt haben.
Es liegt also nicht an fehlenden Benutzerprivilegien, dass nichts in HA ankommt.

**Comment by OlwinFroon** [comment]
Vielleicht das hier? Hab ich grad im Log gefunden.
```
2024-01-02 15:54:46.843 WARNING (MainThread) [py.warnings] /config/custom_components/enpal/config_flow.py:127: RuntimeWarning: coroutine 'check_token' was never awaited
  if not check_token(self.data['enpal_host_ip'], self.data['enpal_host_port'], self.data['enpal_token']):
2024-01-02 15:54:46.936 ERROR (MainThread) [custom_components.enpal.sensor] 'NoneType' object has no attribute 'lower'
```

**Comment by Skipperro** [comment]
Ich habe gerade folgende Email von Enpal Support bekommen: 😞 

> Guten Tag Herr Dylewski,
> 
> vielen Dank für Ihre Geduld. Nach erfolgreicher Bearbeitung Ihrer Anfrage mit der Ticketnummer 11395314 teilen wir Ihnen folgendes mit:
> 
> Bezüglich des Softwareupdates:
> 
> Es ist kein direktes Update im eigentlich Sinne, zur Zeit werden Enpal-Boxen der zweiten Generation verbaut, diese unterscheiden nicht in Funktion jedoch in ihrer Hardware zur ersten Generation. 
> 
> Das Update, auf das Sie sich wahrscheinlich beziehen, ist die Angleichung der Software beider Enpal-Box Generationen auf die der zweiten Generation. Durch die unterschiedliche Hardware ist dies jedoch aufwendiger als ursprünglich veranschlagt. Die Software wird intern entwickelt und das Ausrollen für die Kunden mit einer Enpal-Box der ersten Generation verzögert sich daher entgegen der Planung von 2023 auf 2024, genauere Angaben sind auf Grund der noch ausstehenden Testphase nicht zu machen.
> 
> Wir werden dieses Ticket nun schließen. Sollten Sie noch weitere offene Anliegen haben, werden Sie, sobald es Neuigkeiten gibt, von der entsprechenden Fachabteilung zum jeweiligen Bearbeitungsstand benachrichtigt.
> 
> Bitte haben Sie Verständnis, dass es aufgrund des aktuell sehr hohen Anfragevolumens zu verlängerten Wartezeiten kommen kann. Sie unterstützen uns, indem Sie möglichst von Nachfragen zum jeweiligen Bearbeitungsstand absehen, da diese das Anfragevolumen zusätzlich erhöhen und die Bearbeitungszeit weiter verzögern.
> 
> Vielen Dank für Ihre Mithilfe und Ihr Verständnis.

**Comment by OlwinFroon** [comment]
Mit anderen Worten: die bügeln erstmal die Macken aus der neuen Box bevor sie sich mit der alten befassen.
Ich würde also NICHT damit rechnen, dass wir noch in 2024 zum Zug kommen.

Alles was auf absehbare Zeit bleibt, ist die bestehende Version (wieder) zum Laufen zu bringen.

Tester benötigt? Ich stehe bereit.

**Comment by OlwinFroon** [comment]
Ich hab mir gerade nochmal die Rohdaten aus der grauen Box angesehen, das ist ja wirklich beklagenswert und wenig relevant.
Nichts zur Batterie, nichts zur Wallbox. Damit kann man ja fast GAR nichts anfangen :(

**Comment by gickowtf** [comment]
Naja im Grunde kann dann jeder der ein Update bekommt meine Version nutzen.

**Comment by OlwinFroon** [comment]
Aber bis dahin könnte man trotzdem noch diese Version nutzen ... aber dazu müsste sie funktionieren.
Ich finde es lohnt sich, einen Blick auf das Problem zu werfen. 
Das hier ist allemal besser als nichts!

Ich hab übrigens auch grad ne Mail an Enpal geschickt und mich über den Stand der "Schnittstelle" beschwert.

**Comment by OlwinFroon** [comment]
Ich habe gerade eine Stunde mit dem Top Level Support telefoniert.

Es gibt demnach KEINE konkreten Pläne für eine ordentliche Smart Home Schnittstelle und wir werden auch keine Kontrolle über die Wallbox bekommen. 
Eine fragwürdige strategische Entscheidung, finde ich. 
Jede Baumarkt-Solaranlage lässt sich inzwischen problemlos anbinden.
Ich kann nur hoffen, dass Enpal irgendwann den Fehler einsieht und die Prioritäten entsprechend verlagert.

Mit Ende dieses Telefonats sind jedenfalls alle Verkaufsversprechen mir gegenüber (nicht nur die Schnittstelle, sondern auch die Blackout-Box und die generelle Erweiterungsfähigkeit der Anlage) erstmal geplatzt.


Ob der Abgleich der beiden API-Versionen irgendwann in den nächsten Monaten kommt oder nicht, oder ob die "richtige" Schnittstelle in den nächsten Jahren (!) kommt oder nicht, ... das hilft keinem in diesem Moment.

Also bleibt nur:

1. Hören wir nicht auf, uns beim Support über die unbrauchbare Schnittstelle zu beschweren.
Steter Tropfen und so. Viele leise Stimmen = eine laute Stimme. Vielleicht bewirkt es ja was.
Der gute Mann hat mir versichert, ich wäre der erste der sich in dieser Tiefe für eine Schnittstelle ausgesprochen hätte.
Echt jetzt? Ihr seid dran!

2. Machen wir das Beste aus dem was wir bekommen.
Mehr bekommen wir nämlich erstmal nicht.

**Comment by Skipperro** [comment]
Enpal verwendet Komponenten von Huawei, die sogar ihre eigene Integration für Home Assistant haben.
Das Problem ist, dass das Kommunikationsprotokoll von Huawei nur einen Leser für die Daten zulässt. Enpal erhält die Daten bereits auf seinem PC, so dass Sie die Huawei-Integration nicht nutzen können, um diese Daten in Home Assistant zu erhalten... es sei denn, Sie entfernen den PC von Enpal, setzen die Verbindung zu Ihrem Wechselrichter zurück und integrieren ihn direkt in Ihr LAN, als ob es sich um eine normale Huawei-Installation handeln würde.

Ich vermute, Enpal wird darüber nicht glücklich sein, aber es ist eine Option, die ich in Betracht ziehe.

**Comment by OlwinFroon** [comment]
Darüber haben wir auch geredet. 

Jeder Eingriff in die Hardware ist vertraglich verboten. Die Anlage gehört schließlich Enpal.

Darum darf man auch keinen weiteren Panels aufhängen, weitere Wechselrichter einbauen, die Batterie erweitern oder eine zweite dranhängen, eine Blackout-Box anbauen. Nix davon. Gibt alles massiven Ärger.

Die Homebox abklemmen ist keine Option.
Wenn Du das machen willst musst Du die Anlage erst kaufen.

**Comment by Skipperro** [comment]
Ich habe endlich mein Update von Enpal bekommen! :partying_face: 

@gickowtf - Deine Version funktioniert super. Ich habe merge gemacht und ich kann jetzt weiter arbeiten. Vielen Dank!

**Comment by gickowtf** [comment]
Perfekt 👍
