### ISSUE TITLE
Scan Intervall konfigurierbar?!

### ISSUE THREAD

**Issue by gickowtf** [Skipperro/enpal-homeassistant#2]
Moin, evtl. schaffe ich es heute Abend meinen fork online zu stellen. An einer Sache hänge ich jedoch. Ich möchte den Scan Interval konfigurierbar machen da mir persönlich die 120 Sekunden zu wenig sind.

Das hier war mein Versuch!

`SCAN_INTERVAL = timedelta(seconds=int(config['enpal_interval']))`

**Comment by Skipperro** [comment]
Hast du `enpal_interval` auch in `config_flow.py` konfiguriert?

**Comment by gickowtf** [comment]
Ja hatte ich, das Ding ist das ich bevor ich den interval festlege ich die config laden muss

**Comment by Skipperro** [comment]
Wenn es geht bei dir, dann ist mir nicht klar warum es als "issue" gemeldet ist. Brauchst du irgendwelche Fix von mir, oder willst du gleiche Lösung in mein Repo sehen? Du kannst gerne ein Pull Request machen.

**Comment by Skipperro** [comment]
hmm... ich habe nicht gewusst das GitHub hat Discussionsbereich Feature :) 
Jetzt es ist da: https://github.com/Skipperro/enpal-homeassistant/discussions
