### ISSUE TITLE
Keine Geräte erkannt 

### ISSUE THREAD

**Issue by Bulli78** [Skipperro/enpal-homeassistant#6]
Hallo und guten Tag,
ich bin gerade dabei Ihre enpal Integration zu installieren. Ein token und die Zugangsdaten hab ich von enpal bekommen. Mit der Installation hat auch alles funktioniert. Jedoch bekomme ich keine Entitäten Angezeigt. Wenn ich auf Hacs gehe steht da bei Enpal keine Geräte. Muss ich da noch was ändern?

**Comment by Skipperro** [comment]
Wenn Sie neue Installation von Enpal haben, dann haben Sie neue Datenbank. Meine Integration ist leider nicht mit neue DB Kompatibel. Mehr darüber hier: https://github.com/Skipperro/enpal-homeassistant/issues/1

Sie können diese Fork ausprobieren: https://github.com/gickowtf/enpal-homeassistant
Es sollte mit neue DB funktionieren, ich könnte es aber persönlich nicht testen.

**Comment by Bulli78** [comment]
Hallo und guten Morgen, vielen Dank für die Info. Tatsächlich ist es so das ich eine neue Installation habe. Ich habe die Version getestet, die sie mir empfohlen haben. Leider auch da keine Geräte. Mit der fusion Solar App, kann ich mich auch nicht einloggen. Mal schauen ob enpal da was weiß. MfG Torsten Buhlinger --Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 29.01.24, 15:54 schrieb Skipperro ***@***.***>:

   
  Wenn Sie neue Installation von Enpal haben, dann haben Sie neue Datenbank. Meine Integration ist leider nicht mit neue DB Kompatibel. Mehr darüber hier: #1 
  Sie können diese Fork ausprobieren: https://github.com/gickowtf/enpal-homeassistant Es sollte mit neue DB funktionieren, ich könnte es aber persönlich nicht testen.

**Comment by Skipperro** [comment]
Haben Sie schon Info über aktuelle Leistung und Akku Stand via offizielle Enpal App auf Smartphone? Falls nicht, dann es kann sein, dass Enpal hat die Verbindung noch nicht richtig gemacht. Bei mir hat es damals 1-2 Monate gedauert. 

Auf jeden fall, bei neue Installation können Sie mit https://github.com/gickowtf/enpal-homeassistant mindestens versuchen. Meine Repo wird damit leider nicht funktionieren bis ich ein Update von Enpal kriege.

**Comment by mschuerf** [comment]
Hallo, Wurde das Problem jetzt eigentlich gelöst? Auch ich habe alles installiert, jedoch werden keine Geräte oder Entitäten angezeigt

Grüße

Martin

**Comment by Skipperro** [comment]
@mschuerf Nein, bei mir ist nichts neues. 
Wenn du neue PV-Installation hast, kannst du mit https://github.com/gickowtf/enpal-homeassistant versuchen.

**Comment by Skipperro** [comment]
Ich habe jetzt auch Update von Enpal bekommen und merge von https://github.com/gickowtf/enpal-homeassistant genommen.
