### ISSUE TITLE
Keine Entitäten seit Solar Rel. 8.43.1+243312 (18.11.2024) mit Range -24h

### ISSUE THREAD

**Issue by tbreuer** [Skipperro/enpal-homeassistant#9]
Hallo zusammen,

ich nutze die Enpal-Homeassistant Integration mittlerweile schon länger und bisher hat alles einwandfrei funktioniert.
Seit dem Update Solar Rel. 8.43.1+243312 (18.11.2024) bekomme ich gar keine Entitäten mehr angezeigt (auch nicht mit Version 0.3.0), aber nicht, weil die Bezeichnungen nicht stimmen, sondern die Influx Query gibt eine leere Tabelle zurück bei range(start: -24h). Ändere ich dies auf zum Beispiel range(start: -1000h), erhalte ich wieder alle Entitäten. Die Einträge in der Tabelle datieren auf 2024-10-13T20:17:40. Der Nachteil ist nur, dass alle Entitäten 0 sind und keine Werte enthalten sind. Kann es sein, dass bei meiner Enpal-Anlage keine Daten aktuell in die Influx Datenbank geschrieben werden? Die Enpal-App funktioniert einwandfrei und zeigt auch die korrekten Werte an.

Merkwürdiges Verhalten und ich weiß nicht, worauf dies zurückzuführen ist. Aber ich wollte dies dokumentiere und hier aufbringen, falls auch andere Personen die gleichen Probleme haben sollten.

Viele Grüße

**Comment by HarryH2020** [comment]
Leider funktioniert bei mir nach der Umstellung auf Rel. 8.43.1+243312 (18.11.2024)  auch nichts mehr.
Es werden keine Entitäten mehr angezeigt. Auch mit Version 0.3.0 nicht mehr.
Da ich ziemlicher Laie bin, bin ich völlig ratlos. 


![enpal_ha](https://github.com/user-attachments/assets/3897d463-4a52-4ad2-860d-c5cd7a8723dc)

**Comment by Skipperro** [comment]
Also, wenn range bei -1000h die Tabelen liefert, aber -24h nicht, dann sieht so aus, dass Integration funktioniert nicht, weil InfluxDB von Enpal aktualisiert sich nicht mehr. Sieht so aus, dass etwas mit deine Anlage stimmt nicht. Vielleicht Restart von Enpal-Computer wird es reparieren?

Kannst du in InfluxDB gehen und mir deine Output von diese Befehl schicken?

from(bucket: "solar")
  |> range(start: -1000h)
  |> filter(fn: (r) => r["_field"] == "Cpu.Load")
  |> last()
  
  Beispiel von mir:
  
![image](https://github.com/user-attachments/assets/a2e7c924-a188-4eda-89a8-3ccfc8eb7e18)

**Comment by Skipperro** [comment]
Ich möchte auch sehen ob bei dir bei dem Solar-Anlage Webseite die Daten sind aktuell oder nicht, weil vielleicht nur dein InfluxDB ist tot, aber sonst alles läuft:
![image](https://github.com/user-attachments/assets/50808305-4338-49f7-868f-5cd31cf0c330)

**Comment by tbreuer** [comment]
![image](https://github.com/user-attachments/assets/7fc2d4de-87f9-4f22-9858-ad109c850b2f)

![image](https://github.com/user-attachments/assets/d3419838-d381-4390-b3fa-0374a55a34c2)

**Comment by Skipperro** [comment]
Yup - Webseite hat die neue Werte, aber InfluxDB nicht, deswegen Enpal bekommt noch Daten und dein App funktioniert, aber Home Assistant kann die Werte nicht lesen.

Sag bitte Bescheid on neustart hilft.

**Comment by tbreuer** [comment]
Ein Neustart der Anlage hat auch keinen Erfolg gebracht.
Ich habe den Support von Enpal kontaktiert und versuche aktuell herauszufinden, warum die Influx Datenbank nicht mehr funktioniert.
Hier sieht man nochmal sehr gut, dass keinerlei Daten mehr in der Datenbank gespeichert werden:
![image](https://github.com/user-attachments/assets/7d1d40cc-f547-402b-a092-d55f2131203e)
Ich würde damit das Problem schließen, da der Fehler nicht in der Integration liegt, sondern bei Enpal bzw. in der Influx DB.

**Comment by tbreuer** [comment]
Hallo HarryH2020,
im Webinterface von Enpal unter Message ist die korrekte Uhrzeit eingetragen (aktuelles Datum + Uhrzeit). Nur um eine Stunde verschoben, weil sich die Uhrzeit nicht an Sommer- / Winterzeit anpasst.
Ja es ist echt ärgerlich, dass die Influx DB nicht mehr funktioniert, Enpal aber keine Unterstützung leisten möchte und man selber auch keine Möglichkeit hat das Problem zu beheben.
Grüße

**Comment by Skipperro** [comment]
Der Zeitunterschied zwischen der Enpal-Datenbank und Home Assistant spielt keine Rolle, da diese HA-Integration nicht auf die Zeit in der Datenbank achtet. Sie zieht lediglich die neuesten Datenpunkte und setzt sie in HA als aktuellen Wert für „jetzt“ ein.

Nur während der anfänglichen Suche nach Feldern, die gelesen werden sollen, muss mindestens ein Datenpunkt in den letzten 24 Stunden geliefert worden sein. Das wird jedoch ebenfalls direkt in der InfluxDB berechnet. Selbst wenn das Datum um einige Jahre falsch wäre, würde es trotzdem funktionieren und die Daten als aktuelle Werte in HA einfügen.

Bei mir gibt es auch diese 1-stündige Zeitdifferenz, aber alles funktioniert wie erwartet.
![image](https://github.com/user-attachments/assets/5456fed6-4367-487a-843a-a356cabc96f8)
![image](https://github.com/user-attachments/assets/77830a6d-5463-40e5-a9f0-fc8dac44d8f2)

**Comment by tbreuer** [comment]
Korrekt. In diesem Falle hat es einfach damit zutun, dass seit dem Update irgendwas nicht stimmt (aber auch nicht bei allen, sondern nur in manchen Fällen) und die InfluxDB keinerlei Daten mehr erhält. Damit sind bei mir alle Werte 0 oder "".

**Comment by pooyashahidi** [comment]
@tbreuer  was für Inverter hast du?

**Comment by tbreuer** [comment]
@pooyashahidi Den Huawei SUN2000 8KTL-M1

**Comment by MalteDvl** [comment]
Habs gerade nochmal versucht, meine Influx funktioniert jetzt wieder

**Comment by tbreuer** [comment]
Heute gegen 11 Uhr wurde ein neues Update eingespielt bei mir: Solar Rel. 8.43.3+249078 (28.11.2024)
Damit geht es auch bei mir wieder und Daten werden in der Influx DB gespeichert

**Comment by HealsCodes** [comment]
Klingt nach Glückssache - bei uns läuft ebenfalls diese Version und bisher werden keine neuen Daten in der influxDB hinterlegt.
